- name: Install mongodb
  hosts: all
  become: true
  tasks:
    - name: Add mongodb PGP key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-3.2.asc
        state: present

    - name: Add MongoDB repository into sources list
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu {{ansible_distribution_release}}/mongodb-org/3.2 multiverse
        state: present

    - name: Install mongodb package
      apt:
        name: mongodb-org
        update_cache: yes
      notify:
        - start mongodb
        - enable mongodb

  handlers:
    - name: start mongodb
      service:
        name: mongod
        state: started

    - name: enable mongodb
      service:
        name: mongod
        enabled: yes